### ISSUE TITLE
Minor issue with the array insert

### ISSUE THREAD

**Issue by borisyurkevich** [nyisztor/swift-algorithms#3]
Hello Nyisztor,

I read your book, was a good read thanks. Have question about your quote.

> If you pass in the last index, the new element is appended to the array.

I tried following.

```swift
var list = [0,1,2,3,4,5]
list.insert(42, at: l)
// Outputs [0, 1, 2, 3, 4, 42, 5]
```

As you can see the number is inserted before the last item in array.

**Comment by nyisztor** [comment]
Hi @borisyurkevich,
Your code inserts the value 42 at index 1, which is not the last index. Thus, the actual output should be [0, 42, 1, 2, 3, 4, 5].

The last index can be retrieved using the `endIndex` property. Here's the correct code which produces the result I was talking about:
```
var list = [0,1,2,3,4,5]
list.insert(42, at: list.endIndex)
print(list)
// Output: [0, 1, 2, 3, 4, 5, 42]
```
